// БЛОК 3: КОФЕЙНЫЙ РИТУАЛ И МЕНТАЛЬНЫЙ ВЫКЛЮЧАТЕЛЬ (ОТРЕЗОК 2:52 - 4:59)
const database = [
    { start: 171.6, end: 174, es: "Y por que sin movimientos bruscos", ru: "А почему без резких движений?" },
    { start: 174, end: 181, es: "Porque si me levanto muy rapido me mareo El cuerpo necesita tiempo para adaptarse al cambio de posicion", ru: "Потому что если я встаю слишком быстро, у меня кружится голова. Телу нужно время, чтобы адаптироваться к изменению положения." },
    { start: 181, end: 185, es: "El cuerpo que no esta listo para la verticalidad todavia", ru: "Тело, которое ещё не готово к вертикальному положению." },
    { start: 185, end: 192.2, es: "La verticalidad esa es la palabra perfecta Mi cuerpo a las siete de la mañana rechaza la verticalidad", ru: "Вертикальность — это идеальное слово. Мой организм в 7 часов утра отвергает вертикальность." },
    { start: 192.3, end: 193.8, es: "Y luego que", ru: "А потом что?" },
    { start: 194, end: 200.1, es: "Luego me levanto voy al bano me lavo la cara y aqui viene mi ritual mas importante", ru: "Потом я встаю, иду в ванную, умываюсь, и вот тут наступает мой самый важный ритуал." },
    { start: 200.1, end: 201, es: "Cual", ru: "Какой?" },
    { start: 201, end: 206, es: "El cafe inmediatamente antes de cualquier otra cosa", ru: "Кофе, немедленно, прежде всего остального." },
    { start: 206, end: 208.9, es: "El cafe como primer acto del dia", ru: "Кофе как первое действие за день." },
    { start: 209, end: 217, es: "Primer acto sagrado e inamovible Si por alguna razon no puedo hacer el cafe inmediatamente el dia empieza mal", ru: "Первое действие, священное и неизменное. Если по какой-то причине я не могу сварить кофе сразу, день начинается плохо." },
    { start: 217.6, end: 220, es: "En serio Tan importante es", ru: "Серьёзно? Это настолько важно?" },
    { start: 220.4, end: 225.8, es: "Importantisimo El cafe no es solo una bebida para mi es una senal", ru: "Очень важно. Кофе для меня — это не просто напиток, это сигнал." },
    { start: 226, end: 227.5, es: "Una senal de que", ru: "Сигнал о чём?" },
    { start: 227.6, end: 235.2, es: "Una senal que le mando a mi cerebro de que el dia ha empezado oficialmente que ya paso de la noche al dia", ru: "Сигнал, который я посылаю своему мозгу о том, что день официально начался, что он уже перешёл от ночи к дню." },
    { start: 235.3, end: 239.8, es: "El cafe como interruptor mental lo que activa el modo dia", ru: "Кофе как ментальный выключатель, то, что активирует дневной режим." },
    { start: 239.9, end: 246.9, es: "El interruptor y sin ese interruptor el cerebro sigue en modo noche aunque sean las ocho de la mañana", ru: "Выключатель, и без этого выключателя мозг остаётся в ночном режиме, даже если уже 8 часов утра." },
    { start: 247, end: 250, es: "Y como te preparas el cafe Rapido o con ritual", ru: "А как ты готовишь кофе? Быстро или с ритуалом?" },
    { start: 250.2, end: 255, es: "Con ritual Tengo una cafetera italiana de esas que van en el fuego", ru: "С ритуалом. У меня гейзерная кофеварка, из тех, что ставят на огонь." },
    { start: 255, end: 257.9, es: "La cafetera italiana clasica", ru: "Классическая гейзерная кофеварка." },
    { start: 258, end: 266, es: "La cafetera moca y hay algo muy reconfortante en el sonido que hace when el cafe sube ese borboteo al final", ru: "Кофеварка мока, и есть что-то очень утешительное в звуке, который она издаёт, когда кофе поднимается, в этом бурлении в самом конце." },
    { start: 266, end: 268.7, es: "Ese sonido si que es un activador", ru: "Этот звук действительно пробуждает." },
    { start: 268.8, end: 279, es: "Un activador sensorial y el olor Cuando el cafe empieza a subir y el olor llena la cocina algo en mi se activa aunque todavia este medio dormido", ru: "Сенсорный активатор, и запах. Когда кофе начинает подниматься и запах наполняет кухню, во мне что-то просыпается, хотя я всё ещё полусонный." },
    { start: 279.5, end: 283.5, es: "El olfato como el primer sentido que despierta del todo", ru: "Обоняние как первое чувство, которое просыпается полностью." },
    { start: 283.6, end: 289, es: "El primero y ese olor a cafe por la mañana es una de mis cosas favoritas de existir", ru: "Первое, и этот утренний запах кофе — одна из моих самых любимых вещей в существовании." },
    { start: 289, end: 291.3, es: "De existir eso es grande", ru: "В существовании — это громко сказано." },
    { start: 291.4, end: 299, es: "Es grande pero es verdad Ese olor a cafe recien hecho en la cocina de mañana es uno de los pequenos lujos de la vida diaria", ru: "Громко, но это правда. Этот запах свежесваренного кофе на кухне по утрам — одна из маленьких роскошей повседневной жизни." }
];
