// БЛОК 4: ИСПАНСКИЙ ЗАВТРАК И СЕКРЕТ ЖАВОРОНКА (ОТРЕЗОК 4:52 - 6:52)
const database = [
    { start: 292, end: 299, es: "Es grande pero es verdad Ese olor a cafe recien hecho en la cocina de mañana es uno de los pequenos lujos de la vida diaria", ru: "Громко, но это правда. Этот запах свежесваренного кофе на кухне по утрам — одна из маленьких роскошей повседневной жизни." },
    { start: 299, end: 302.7, es: "Y desayunas mientras tomas el cafe o solo el cafe", ru: "А ты завтракаешь, пока пьёшь кофе, или только кофе?" },
    { start: 302.8, end: 309.4, es: "Depende del dia Si tengo tiempo desayuno bien Tostadas con tomate y aceite un poco de fruta", ru: "Зависит от дня. Если есть время, завтракаю хорошо. Тосты с помидором и маслом, немного фруктов." },
    { start: 309.5, end: 311.8, es: "El desayuno espanol clasico", ru: "Классический испанский завтрак." },
    { start: 312, end: 316, es: "Exacto Y si no tengo tiempo solo el cafe y salgo corriendo", ru: "Точно. А если времени нет, только кофе и выбегаю." },
    { start: 316, end: 318.8, es: "El desayuno de supervivencia", ru: "Завтрак на выживание." },
    { start: 319, end: 324, es: "El desayuno de supervivencia Solo el cafe y ya me las arreglo hasta la hora de comer", ru: "Завтрак на выживание. Только кофе, и как-нибудь перебиваюсь до обеда." },
    { start: 324, end: 327, es: "Eso no es muy recomendable sabes", ru: "Это не очень полезно, знаешь ли." },
    { start: 327, end: 332, es: "Lo se Los nutricionistas dicen que el desayuno es la comida mas importante del dia", ru: "Знаю. Диетологи говорят, что завтрак — самый важный приём пищи за день." },
    { start: 332.1, end: 333.8, es: "Lo dicen siempre", ru: "Они всегда это говорят." },
    { start: 333.9, end: 343, es: "Y tienen razon Los dias que desayuno bien rindo mucho mas por la mañana Los dias que solo tomo el cafe a las once ya estoy con el estomago protestando", ru: "И они правы. В те дни, когда я хорошо завтракаю, я работаю гораздо продуктивнее утром. В дни, когда пью только кофе, в одиннадцать часов желудок уже протестует." },
    { start: 343, end: 347.5, es: "El estomago que protesta Esa imagen es perfecta", ru: "Протестующий желудок. Этот образ идеален." },
    { start: 347.6, end: 353, es: "Protestando con ruidos en el momento mas silencioso de la reunion", ru: "Протестующий урчанием в самый тихий момент совещания." },
    { start: 353, end: 356, es: "En el momento mas silencioso siempre", ru: "В самый тихий момент, всегда." },
    { start: 356, end: 364, es: "Sin falta El cuerpo tiene un sentido del humor malisimo Oye y tu Cuentame tu mañana Que dijiste que eres de mañanas", ru: "Обязательно. У тела ужасное чувство юмора. Слушай, а ты? Расскажи про своё утро. Ты же сказала, что ты жаворонок?" },
    { start: 364, end: 366.6, es: "Mi mañana empieza antes que la tuya", ru: "Моё утро начинается раньше твоего." },
    { start: 366.7, end: 368, es: "A que hora te levantas", ru: "В каком часу ты встаёшь?" },
    { start: 368, end: 369.2, es: "A las seis y cuarto", ru: "В четверть седьмого (в шесть пятнадцать)." },
    { start: 369.3, end: 371, es: "Ay eso duele escucharlo", ru: "Ай, это даже слушать больно." },
    { start: 372, end: 374, es: "Para mi es completamente normal", ru: "Для меня это совершенно нормально." },
    { start: 374, end: 377.9, es: "Las seis y cuarto de la mañana no es normal Es heroico", ru: "Шесть пятнадцать утра — это ненормально. Это героически." },
    { start: 378, end: 381, es: "No es heroico Es que me acuesto pronto", ru: "Это не героически. Просто я ложусь рано." },
    { start: 381, end: 381.8, es: "A que hora", ru: "В каком часу?" },
    { start: 381.9, end: 384.9, es: "A las diez A las diez y media como muy tarde", ru: "В десять. В пол-одиннадцатого самое позднее." },
    { start: 385, end: 386.4, es: "Las diez de la noche", ru: "В десять вечера?" },
    { start: 386.6, end: 392, es: "Las diez de la noche Y duermo entre ocho y ocho horas y media Por eso me levanto bien", ru: "В десять вечера. И сплю от восьми до восьми с половиной часов. Поэтому встаю хорошо." },
    { start: 392.1, end: 397, es: "O sea el secreto no es levantarse temprano Es acostarse temprano", ru: "То есть секрет не в том, чтобы вставать рано. А в том, чтобы ложиться рано." },
    { start: 397, end: 403, es: "El secreto esta en acostarse Si duermes tus horas levantarte temprano no es un sacrificio", ru: "Секрет в том, когда ложиться. Если ты высыпаешь свои часы, ранний подъём — это не жертва." },
    { start: 403, end: 409.6, es: "Y yo me acuesto tarde porque soy de noches Y entonces levantarme temprano es un sacrificio enorme", ru: "А я ложусь поздно, потому что я полуночник. И тогда ранний подъём для меня — это огромная жертва." },
    { start: 410, end: 412, es: "Es un ciclo dificil de romper", ru: "Это замкнутый круг, который трудно разорвать." }
];
